총 만들기 완료
kodomomo/Assignment pull request #8
Opened 2021-10-15 04:30 UTC by oidhen

2021-10-15 05:35 UTC, mallycrip commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/factory/Factory.java
> +    public Gun gun;
Factory 에서 Gun을 가지고 있을 필요가 있을까요

2021-10-15 05:35 UTC, mallycrip commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/factory/Factory.java
> +        }
이렇게 사용한다면 Factory.gun 으로 객체에 접근하는데 이게 원하는 방향이 맞나요

2021-10-15 05:37 UTC, mallycrip commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/Main.java
> +        akFactory.gun.reload();
총을 만드는 공장에서 ak 하나 만든다고 ak 공장, m4만든다고 m4공장 이렇게 공장을 늘리는게 맞을까요?
설계도가 들어가면 어쩌피 그 설계도에 맞는 총만 나올텐데 굳이 공장을 증설할 이유가 없는거같죠?

2021-10-15 05:38 UTC, mallycrip commented
그리고 커밋할 때 통째로 커밋하지 말아주세요.

2021-10-15 09:55 UTC, o-ozogie requested changes
🦾

2021-10-15 09:55 UTC, o-ozogie commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/Factory.java
> +        String[] gunInfo = {gunBlueprint.getName(),gunBlueprint.getColor(),gunBlueprint.getTypeOfBullet()};
이렇게 코딩을 하면 암시적으로 0번 인덱스에는 총 이름, 1번 인덱스에는 총 색깔, 2번 인덱스에는 총알 종류가 들어있는 길이 3짜리 배열과 같은 구체적인 정보에 의존하게 되어서 총기 정보의 변경이 생겼을 때 유연하게 대처하지 못하게 됩니다.
총기의 생성자에서 GunBlueprint를 가지고 총기에 대한 정보를 참조하여 총기 객체를 리턴하는 식으로 구현하는건 어떨까요?

2021-10-15 09:55 UTC, o-ozogie commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/Main.java
> +    GunBlueprint[] gunBlueprints = {GunBlueprint.UMP,GunBlueprint.AK47,GunBlueprint.M4A1,GunBlueprint.AWP};
이거 배열에 넣는 것보다 객체 만들때나 설계도 변경할 때 넣어주는게 좋은 것 같아요. 어차피 설계도가 Enum? 상수?로 관리되고 있으니까 괜찮을듯 합니다!

2021-10-19 05:16 UTC, mallycrip reviewed
👎👎👎👎👎

2021-10-19 05:16 UTC, mallycrip commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/Factory.java
> +    }
이 코드가
```java
public void changeGunBlueprint(GunBlueprint gunBlueprint){
          this.gunBlueprint = gunBlueprint;   
}
```
랑 다른게 머임? 🤔🤔

2021-10-19 05:16 UTC, mallycrip commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/Main.java
> +    ak.getColor();
굳이 change하고 makeAK해야함?
걍 블루프린트 넣는대로 자동으로 나오면 안됨?

2021-10-20 01:00 UTC, mallycrip reviewed
👎👎👎👎👎

2021-10-20 01:15 UTC, o-ozogie requested changes

2021-10-20 01:15 UTC, o-ozogie commented on OO/설계도로총만들기/createGunByBlueprint/src/main/java/createGunByBlueprint/Factory.java
> +    }
Gunblueprint를 생성자 인자로 받아서 Factory 객체는 총기 정보를 가지고 있는 blueprint를 들고 있으니까 makeXXX로 총기마다 메서드를 빼는것보다 makeGun 해서 설계도에 있는 정보를 바탕으로 민기말대로 분기문으로 총기 리턴하는게 좋을듯

2021-10-20 01:27 UTC, mallycrip requested changes
암튼 고쳐라

2021-11-14 23:47 UTC, closed without merging

2021-11-15 00:43 UTC, oidhen commented
.